FROM nginx

## Create the directory if doesn't exists
## Then CD into directory
WORKDIR /usr/share/nginx/html

## RUN ["echo","<h1>Hello World</h1>",">","index.html"]
# COPY SourcePath DestPath
COPY index.html index.html